In [1]:
import numpy as np
from NeuralNet import *
from random import randint
from random import random
import math

training_set  = open("train-images.idx3-ubyte","r")
dt = np.dtype('>i4')
np.fromfile(training_set, dt, count=4)
dt = np.dtype('>u1')
images = np.fromfile(training_set, dt)
dim = 28
samples = 60000
print(len(images), dim*dim*samples)

numbers = images.reshape((samples, dim*dim))/256
# numbers = (numbers>0).astype(int)
np.savetxt('result.txt', numbers[99].reshape((dim,dim)), fmt='%d')

training_labels  = open("train-labels.idx1-ubyte","r")
dt = np.dtype('>i4')
labels = np.fromfile(training_labels, dt, count=2)
dt = np.dtype('>i1')
labels = np.fromfile(training_labels, dt)
label = np.zeros((samples, 10))
for i in range(0,samples):
    label[i,labels[i]] = 1

47040000 47040000


In [14]:

# How should I sort between 0-9 when all I have is a simple probability maker so far?
# One way is to have 10 outputs, and encode the labels into boxes

net = LayeredNet([28*28,10,5,10])

save = net.synapse
prev = 0
count = 0
succ = []
shuffled = np.random.permutation(np.arange(0,samples,10))
frac = 1/60 # how much of the set are we going to train on
for i in range(5):
    net.grow(50)
    frac = frac * 2
    for i in shuffled[0:round(samples*frac)]:
        save = net.synapse
        lab = np.array(np.matrix(label[i:i+10,:]))
        for j in range(1): # Do multiple steps of learning
            net.learn(numbers[i:i+10],lab)
        net.success_rate(numbers[0:round(samples*frac)],label[0:round(samples*frac)])
        choice = "Improvement found"
        heat = (samples*frac-i)/(samples*frac)
        curr = net.success_probability
        if(prev > curr):
            if random()/(prev-curr) > heat: # todo: needs proper scheme for weighting really bad learning cases
                prev = curr
                choice = "Choosing worse"
            else:
                net.synapse = save
                choice = "Not choosing worse"
        else:
            prev = net.success_probability
        succ.append(prev)
        print("Iter:", i, choice, prev, end='\r')


KeyboardInterrupt: 

In [3]:
net.synapse = save
start = 0
end = 60000
lab = np.array(np.matrix(label[start:end,:]))
net.success_rate(numbers[start:end],lab)
print(net.success_probability)

print("Output vs True\n")
for i in range(5):
    print(np.round(net.layer[-1][i]), ":", lab[i])

0.7795166666666666
Output vs True

[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.] : [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.] : [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.] : [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.] : [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.] : [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]


In [4]:
testing_set  = open("t10k-images.idx3-ubyte","r")
dt = np.dtype('>i4')
np.fromfile(testing_set, dt, count=4)
dt = np.dtype('>u1')
images = np.fromfile(testing_set, dt)
num_images = 10000
dim = 28
print(len(images), dim*dim*num_images)

numbers = images.reshape((num_images, dim*dim))
numbers = (numbers>0).astype(int)
np.savetxt('result.txt', numbers[99].reshape((28,28)), fmt='%d')

testing_labels  = open("t10k-labels.idx1-ubyte","r")
dt = np.dtype('>i4')
labels = np.fromfile(testing_labels, dt, count=2)
dt = np.dtype('>i1')
labels = np.fromfile(testing_labels, dt)
label = np.zeros((num_images, 10))
for i in range(0,num_images):
    label[i,labels[i]] = 1

net.success_rate(numbers,label)
print(net.success_probability)

7840000 7840000
0.7329


In [10]:
net.synapse = goodsave
save = net.synapse
net.grow(0)
prev = 0
count = 0
succ = []
shuffled = np.random.permutation(np.arange(0,samples,10))
frac = 1/60 # how much of the set are we going to train on
for i in shuffled[0:round(samples*frac)]:
    save = net.synapse
    lab = np.array(np.matrix(label[i:i+10,:]))
    for j in range(1): # Do multiple steps of learning
        net.learn(numbers[i:i+10],lab)
    net.success_rate(numbers[0:round(samples*frac)],label[0:round(samples*frac)])
    choice = "Improvement found"
    heat = (samples*frac-i)/(samples*frac)
    curr = net.success_probability
    if(prev > curr):
        if random()/(prev-curr) > heat: # todo: needs proper scheme for weighting really bad learning cases
            prev = curr
            choice = "Choosing worse"
        else:
            net.synapse = save
            choice = "Not choosing worse"
    else:
        prev = net.success_probability
    succ.append(prev)
    print("Iter:", i, choice, prev, end='\r')

KeyboardInterrupt: 

In [13]:
print(net.synapse)

[array([[-0.94283567, -0.2009351 , -0.10632489, ...,  0.76103897,
        -0.42999271,  0.93674705],
       [ 0.77982399,  0.60534272, -0.47983522, ...,  0.91339005,
         0.24979682,  0.30468672],
       [-0.65785646, -0.01782286, -0.49871319, ..., -0.13778499,
         0.51711439, -0.95669331],
       ..., 
       [-0.25905531,  0.25442929,  0.19316922, ..., -0.08733383,
         0.9939037 , -0.06234686],
       [ 0.01381524, -0.90326338, -0.67586758, ..., -0.0727404 ,
         0.77084371,  0.14909229],
       [-0.31723496,  0.82566369,  0.71964071, ..., -0.80110587,
         0.67327074, -0.84628036]]), array([[ -1.64577713e-03,   3.14664480e+00,   4.98231537e-01, ...,
         -6.08734705e-01,  -7.52726300e-01,  -1.75238724e-01],
       [  1.05895072e+00,   1.88247480e-01,   9.38221068e-01, ...,
         -5.61082205e-01,   1.81964874e-01,   5.03536512e-01],
       [  2.29980756e+00,   2.55885260e-02,  -4.07881819e-01, ...,
         -1.29188375e-01,   7.45280167e-01,   3.08045453e