In [6]:
import numpy as np
from NeuralNet import *
from random import randint
import math

training_set  = open("train-images.idx3-ubyte","r")
dt = np.dtype('>i4')
np.fromfile(training_set, dt, count=4)
dt = np.dtype('>u1')
images = np.fromfile(training_set, dt)
print(len(images), 28*28*60000)

numbers = images.reshape((60000, 28*28))
numbers = (numbers>0).astype(int)
np.savetxt('result.txt', numbers[99].reshape((28,28)), fmt='%d')

training_labels  = open("train-labels.idx1-ubyte","r")
dt = np.dtype('>i4')
labels = np.fromfile(training_labels, dt, count=2)
dt = np.dtype('>i1')
labels = np.fromfile(training_labels, dt)
label = np.zeros((60000, 10))
for i in range(0,60000):
    label[i,labels[i]] = 1

47040000 47040000


In [28]:

# How should I sort between 0-9 when all I have is a simple probability maker so far?
# One way is to have 10 outputs, and encode the labels into boxes

net = LayeredNet([28*28,20,10,10])

save = net.synapse
prev = 0
count = 0
succ = []
samples = 60000
for i in range(0,samples,10):
    save = net.synapse
    lab = np.array(np.matrix(label[i:i+10,:]))
    for j in range(1): # Do multiple steps of learning
        net.learn(numbers[i:i+10],lab)
    net.success_rate(numbers[0:samples],label[0:samples])
    choice = "Improvement found"
    heat = 10*(samples/2-i)/(samples)
    curr = net.success_probability
    if(prev > curr):
        if randint(0, 50)*(prev-curr) < heat:
            prev = curr
            choice = "Choosing worse"
        else:
            net.synapse = save
            choice = "Not choosing worse"
    else:
        prev = net.success_probability
    succ.append(prev)
    print("Iter:", i, choice, prev, end='\r')
        
        
print(succ)
print("Output After Training:\n", np.round(net.layer[-1]))
print("True:\n", lab)


KeyboardInterrupt: 

In [30]:
net.synapse = save
start = 0
end = 60000
lab = np.array(np.matrix(label[start:end,:]))
net.success_rate(numbers[start:end],lab)
print(net.success_probability)

print("Output vs True\n")
for i in range(5):
    print(np.round(net.layer[-1][i]), ":", lab[i])

0.718
Output vs True

[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.] : [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.] : [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.] : [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.] : [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.] : [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [35]:
testing_set  = open("t10k-images.idx3-ubyte","r")
dt = np.dtype('>i4')
np.fromfile(testing_set, dt, count=4)
dt = np.dtype('>u1')
images = np.fromfile(testing_set, dt)
num_images = 10000
dim = 28
print(len(images), dim*dim*num_images)

numbers = images.reshape((num_images, dim*dim))
numbers = (numbers>0).astype(int)
np.savetxt('result.txt', numbers[99].reshape((28,28)), fmt='%d')

testing_labels  = open("t10k-labels.idx1-ubyte","r")
dt = np.dtype('>i4')
labels = np.fromfile(testing_labels, dt, count=2)
dt = np.dtype('>i1')
labels = np.fromfile(testing_labels, dt)
label = np.zeros((num_images, 10))
for i in range(0,num_images):
    label[i,labels[i]] = 1

net.success_rate(numbers,label)
print(net.success_probability)

7840000 7840000
0.718
